
DROP TABLE T_JPS_CONSULTA CASCADE CONSTRAINTS
;

DROP TABLE T_JPS_FEEDBACK CASCADE CONSTRAINTS
;

DROP TABLE T_JPS_FUNCIONARIO CASCADE CONSTRAINTS
;

DROP TABLE T_JPS_MEDICO CASCADE CONSTRAINTS
;

DROP TABLE T_JPS_PACIENTE CASCADE CONSTRAINTS
;